version: '3.8'

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development 
    volumes:
      - .:/app
    restart: unless-stopped
